function varargout = DIG_Out_Line(varargin)
%DIG_OUT_LINE calls nidaq library with the appropriate arguments.
%
% The C declaration for this function is the following:
%	 extern i16 _stdcall DIG_Out_Line ( i16 slot , i16 port , i16 linenum , i16 state ); 
%
% The MATLAB Declaration looks like the following:
%	int16 DIG_Out_Line(int16, int16, int16, int16)
%
% This function will call loadlibrary on the library if needed.
% This file is automatically generated by the loadlibrarygui.
%
%   See also
%   LOADLIBRARY, UNLOADLIBRARY, LOADNIDAQ, UNLOADNIDAQ

%
%
% $Author: $
% $Revision: $
% $Date: 01-Apr-2010 12:03:15 $
%
% Local Functions Defined:
%
%
% $Notes:
%
%
%
%
% $EndNotes
%
% $Description:
%
%
%
%
% $EndDescription


if nargin==0;
	help(mfilename);
	return;
end;


% If Library is loaded already unload it.

if ~libisloaded('NI')
	loadNI;
end;


if nargin~=4;
	error(mfilename:WrongNumberIn,'Incorrect number of input arguments.');
end;

if nargout~=1;
	error(mfilename:WrongNumberOut,'Incorrect number of output arguments.');
end;

% Call external function in loaded DLL.
[varargout{1}]=calllib('NI','DIG_Out_Line',varargin{:});

