function param = loadni;
%LOADNI calls loadlibrary with the appropriate input arguments.
%
% This function will call loadlibrary if needed with the predefined protocal file.
% This file is automatically generated by the loadlibrarygui.
%
%   See also
%   LOADLIBRARY, UNLOADLIBRARY, UNLOADNI

%
%
% $Author: $
% $Revision: $
% $Date: 24-Dec-2002 11:30:13 $
%
% Local Functions Defined:
%
%
% $Notes:
%
%
%
%
% $EndNotes
%
% $Description:
%
%
%
%
% $EndDescription


% If Library is loaded already unload it.

if libisloaded('ni')
	unloadni;
end;

warningSetting1 = warning('off','MATLAB:loadlibrary:functionnotfound');
warningSetting2 = warning('off','MATLAB:loadlibrary:typenotfound');
warningSetting3 = warning('off','MATLAB:loadlibrary:enumexists');
% Load the library.
loadlibrary('C:\WINNT\system32\nidaq32.dll',@ni,'alias','ni');

if nargout
	param = loadNIcns('D:\Applications\National Instruments\NI-DAQ\Include\nidaqcns.h');
end
warning(warningSetting1);
warning(warningSetting2);
warning(warningSetting3);
