function unloadni
%UNLOADNI calls loadlibrary with the appropriate input arguments.
%
% This function will call unloadlibrary on the library defined as ni
%
% You must have cleared memory and not have any varables defined using 
%	this library to work.
%
% This file is automatically generated by the loadlibrarygui.
%
%   See also
%   LOADLIBRARY, UNLOADLIBRARY, LOADNI

%
%
% $Author: $
% $Revision: $
% $Date: 24-Dec-2002 11:30:13 $
%
% Local Functions Defined:
%
%
% $Notes:
%
%
%
%
% $EndNotes
%
% $Description:
%
%
%
%
% $EndDescription
% unload the library.
unloadlibrary('ni');
